"""muhasebe tablolari

Revision ID: 04c0b3a051ae
Revises: 216c3af152f9
Create Date: 2026-04-29 23:38:17.316346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c0b3a051ae'
down_revision = '216c3af152f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=120), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('bakiye', sa.Float(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cari_hareket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=10), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gelir_gider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=10), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.String(length=300), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gelir_gider')
    op.drop_table('cari_hareket')
    op.drop_table('cari')
    # ### end Alembic commands ###
