"""mulk yasal_durum

Revision ID: 168d6547f9bc
Revises: 3ba7d9d7c2e0
Create Date: 2026-05-02 00:45:01.901631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168d6547f9bc'
down_revision = '3ba7d9d7c2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mulk', sa.Column('yasal_durum', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mulk', 'yasal_durum')
    # ### end Alembic commands ###
