"""islem_log tablosu

Revision ID: 1954d56b2712
Revises: ce18c70f4ed1
Create Date: 2026-04-29 22:42:43.929090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1954d56b2712'
down_revision = 'ce18c70f4ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islem_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('maliyet_usd', sa.Float(), nullable=True),
    sa.Column('kredi_tutar', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('islem_log')
    # ### end Alembic commands ###
