"""musteri detaylar json

Revision ID: 216c3af152f9
Revises: 666e06c14606
Create Date: 2026-04-29 23:17:19.780309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216c3af152f9'
down_revision = '666e06c14606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musteri', sa.Column('detaylar', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musteri', 'detaylar')
    # ### end Alembic commands ###
