"""envanter ve geri bildirim

Revision ID: 3b98fa5e7251
Revises: 17f852b998c4
Create Date: 2026-04-30 18:56:26.746426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b98fa5e7251'
down_revision = '17f852b998c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envanter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=120), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('miktar', sa.Integer(), nullable=True),
    sa.Column('min_miktar', sa.Integer(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geri_bildirim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('yer_gosterme_id', sa.Integer(), nullable=True),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('yorum', sa.Text(), nullable=True),
    sa.Column('ilgi_durumu', sa.String(length=20), nullable=True),
    sa.Column('sonraki_adim', sa.String(length=50), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.ForeignKeyConstraint(['yer_gosterme_id'], ['yer_gosterme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geri_bildirim')
    op.drop_table('envanter')
    # ### end Alembic commands ###
