"""kullanici_ayar ve sistem_parametre

Revision ID: 3ba7d9d7c2e0
Revises: 4bf880fa6fda
Create Date: 2026-05-01 14:43:51.410624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba7d9d7c2e0'
down_revision = '4bf880fa6fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistem_parametre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('deger', sa.Text(), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('guncelleme', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anahtar')
    )
    op.create_table('kullanici_ayar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ayarlar', sa.JSON(), nullable=True),
    sa.Column('guncelleme', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emlakci_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici_ayar')
    op.drop_table('sistem_parametre')
    # ### end Alembic commands ###
