"""musteri_hafiza ve konusma_state

Revision ID: 4bf880fa6fda
Revises: f68c57f4836b
Create Date: 2026-05-01 01:06:12.347261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf880fa6fda'
down_revision = 'f68c57f4836b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konusma_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('son_islem', sa.String(length=50), nullable=True),
    sa.Column('son_musteri_id', sa.Integer(), nullable=True),
    sa.Column('son_mulk_id', sa.Integer(), nullable=True),
    sa.Column('son_arama', sa.JSON(), nullable=True),
    sa.Column('bekleyen', sa.JSON(), nullable=True),
    sa.Column('baglam', sa.JSON(), nullable=True),
    sa.Column('guncelleme', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emlakci_id')
    )
    op.create_table('musteri_hafiza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musteri_hafiza')
    op.drop_table('konusma_state')
    # ### end Alembic commands ###
