"""danisman ve musteri_atama

Revision ID: 4e3d7d6eec54
Revises: 3b98fa5e7251
Create Date: 2026-04-30 19:13:13.618805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3d7d6eec54'
down_revision = '3b98fa5e7251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danisman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('uzmanlik', sa.String(length=100), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri_atama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('danisman_id', sa.Integer(), nullable=False),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['danisman_id'], ['danisman.id'], ),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musteri_atama')
    op.drop_table('danisman')
    # ### end Alembic commands ###
