"""mulk detaylar json

Revision ID: 666e06c14606
Revises: 72725a98b303
Create Date: 2026-04-29 23:09:37.867127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666e06c14606'
down_revision = '72725a98b303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mulk', sa.Column('detaylar', sa.JSON(), nullable=True))
    op.drop_column('mulk', 'mutfak')
    op.drop_column('mulk', 'kullanim_durumu')
    op.drop_column('mulk', 'otopark')
    op.drop_column('mulk', 'site_icerisinde')
    op.drop_column('mulk', 'brut_metrekare')
    op.drop_column('mulk', 'bina_yasi')
    op.drop_column('mulk', 'isinma')
    op.drop_column('mulk', 'site_adi')
    op.drop_column('mulk', 'aidat')
    op.drop_column('mulk', 'kimden')
    op.drop_column('mulk', 'balkon')
    op.drop_column('mulk', 'asansor')
    op.drop_column('mulk', 'kat_sayisi')
    op.drop_column('mulk', 'krediye_uygun')
    op.drop_column('mulk', 'tapu_durumu')
    op.drop_column('mulk', 'takas')
    op.drop_column('mulk', 'esyali')
    op.drop_column('mulk', 'net_metrekare')
    op.drop_column('mulk', 'bulundugu_kat')
    op.drop_column('mulk', 'banyo_sayisi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mulk', sa.Column('banyo_sayisi', sa.INTEGER(), nullable=True))
    op.add_column('mulk', sa.Column('bulundugu_kat', sa.VARCHAR(length=30), nullable=True))
    op.add_column('mulk', sa.Column('net_metrekare', sa.FLOAT(), nullable=True))
    op.add_column('mulk', sa.Column('esyali', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('takas', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('tapu_durumu', sa.VARCHAR(length=50), nullable=True))
    op.add_column('mulk', sa.Column('krediye_uygun', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('kat_sayisi', sa.INTEGER(), nullable=True))
    op.add_column('mulk', sa.Column('asansor', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('balkon', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('kimden', sa.VARCHAR(length=30), nullable=True))
    op.add_column('mulk', sa.Column('aidat', sa.FLOAT(), nullable=True))
    op.add_column('mulk', sa.Column('site_adi', sa.VARCHAR(length=100), nullable=True))
    op.add_column('mulk', sa.Column('isinma', sa.VARCHAR(length=50), nullable=True))
    op.add_column('mulk', sa.Column('bina_yasi', sa.INTEGER(), nullable=True))
    op.add_column('mulk', sa.Column('brut_metrekare', sa.FLOAT(), nullable=True))
    op.add_column('mulk', sa.Column('site_icerisinde', sa.VARCHAR(length=10), nullable=True))
    op.add_column('mulk', sa.Column('otopark', sa.VARCHAR(length=30), nullable=True))
    op.add_column('mulk', sa.Column('kullanim_durumu', sa.VARCHAR(length=20), nullable=True))
    op.add_column('mulk', sa.Column('mutfak', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('mulk', 'detaylar')
    # ### end Alembic commands ###
