"""mulk detay alanlari

Revision ID: 72725a98b303
Revises: 1954d56b2712
Create Date: 2026-04-29 23:02:48.091771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72725a98b303'
down_revision = '1954d56b2712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mulk', sa.Column('brut_metrekare', sa.Float(), nullable=True))
    op.add_column('mulk', sa.Column('net_metrekare', sa.Float(), nullable=True))
    op.add_column('mulk', sa.Column('bina_yasi', sa.Integer(), nullable=True))
    op.add_column('mulk', sa.Column('bulundugu_kat', sa.String(length=30), nullable=True))
    op.add_column('mulk', sa.Column('kat_sayisi', sa.Integer(), nullable=True))
    op.add_column('mulk', sa.Column('isinma', sa.String(length=50), nullable=True))
    op.add_column('mulk', sa.Column('banyo_sayisi', sa.Integer(), nullable=True))
    op.add_column('mulk', sa.Column('mutfak', sa.String(length=30), nullable=True))
    op.add_column('mulk', sa.Column('balkon', sa.String(length=10), nullable=True))
    op.add_column('mulk', sa.Column('asansor', sa.String(length=10), nullable=True))
    op.add_column('mulk', sa.Column('otopark', sa.String(length=30), nullable=True))
    op.add_column('mulk', sa.Column('esyali', sa.String(length=10), nullable=True))
    op.add_column('mulk', sa.Column('kullanim_durumu', sa.String(length=20), nullable=True))
    op.add_column('mulk', sa.Column('site_icerisinde', sa.String(length=10), nullable=True))
    op.add_column('mulk', sa.Column('site_adi', sa.String(length=100), nullable=True))
    op.add_column('mulk', sa.Column('aidat', sa.Float(), nullable=True))
    op.add_column('mulk', sa.Column('krediye_uygun', sa.String(length=10), nullable=True))
    op.add_column('mulk', sa.Column('tapu_durumu', sa.String(length=50), nullable=True))
    op.add_column('mulk', sa.Column('kimden', sa.String(length=30), nullable=True))
    op.add_column('mulk', sa.Column('takas', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mulk', 'takas')
    op.drop_column('mulk', 'kimden')
    op.drop_column('mulk', 'tapu_durumu')
    op.drop_column('mulk', 'krediye_uygun')
    op.drop_column('mulk', 'aidat')
    op.drop_column('mulk', 'site_adi')
    op.drop_column('mulk', 'site_icerisinde')
    op.drop_column('mulk', 'kullanim_durumu')
    op.drop_column('mulk', 'esyali')
    op.drop_column('mulk', 'otopark')
    op.drop_column('mulk', 'asansor')
    op.drop_column('mulk', 'balkon')
    op.drop_column('mulk', 'mutfak')
    op.drop_column('mulk', 'banyo_sayisi')
    op.drop_column('mulk', 'isinma')
    op.drop_column('mulk', 'kat_sayisi')
    op.drop_column('mulk', 'bulundugu_kat')
    op.drop_column('mulk', 'bina_yasi')
    op.drop_column('mulk', 'net_metrekare')
    op.drop_column('mulk', 'brut_metrekare')
    # ### end Alembic commands ###
