"""mulk grup alani

Revision ID: 7b417e3d580a
Revises: 83085e459b94
Create Date: 2026-04-30 18:06:39.012060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b417e3d580a'
down_revision = '83085e459b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mulk', sa.Column('grup', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mulk', 'grup')
    # ### end Alembic commands ###
