"""fatura tablosu

Revision ID: 83085e459b94
Revises: c7afe58f5b21
Create Date: 2026-04-30 02:22:37.216785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83085e459b94'
down_revision = 'c7afe58f5b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('alici_ad', sa.String(length=120), nullable=True),
    sa.Column('alici_adres', sa.Text(), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=True),
    sa.Column('kdv_oran', sa.Integer(), nullable=True),
    sa.Column('kdv_tutar', sa.Float(), nullable=True),
    sa.Column('toplam', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=15), nullable=True),
    sa.Column('vade_tarihi', sa.DateTime(), nullable=True),
    sa.Column('odeme_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kalemler', sa.JSON(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fatura')
    # ### end Alembic commands ###
