"""egitim tablolari

Revision ID: 9055550a6f21
Revises: f2ec55c20106
Create Date: 2026-04-30 00:07:49.681429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9055550a6f21'
down_revision = 'f2ec55c20106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ogrenilen_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('islem', sa.String(length=50), nullable=False),
    sa.Column('kaynak', sa.String(length=20), nullable=True),
    sa.Column('kullanim', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diyalog_kayit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('mesaj_norm', sa.Text(), nullable=True),
    sa.Column('islem', sa.String(length=50), nullable=False),
    sa.Column('basarili', sa.Boolean(), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diyalog_kayit')
    op.drop_table('ogrenilen_pattern')
    # ### end Alembic commands ###
