"""musteri grup alani

Revision ID: a7d5c8da5030
Revises: e14cf58db7ac
Create Date: 2026-04-30 01:56:13.121923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d5c8da5030'
down_revision = 'e14cf58db7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musteri', sa.Column('grup', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musteri', 'grup')
    # ### end Alembic commands ###
