"""init

Revision ID: b5523360857c
Revises: 
Create Date: 2026-04-27 15:16:24.279064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5523360857c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emlakci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('sifre_hash', sa.String(length=256), nullable=False),
    sa.Column('yetki_no', sa.String(length=50), nullable=True),
    sa.Column('acente_adi', sa.String(length=120), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kredi', sa.Float(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefon')
    )
    op.create_table('konusma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('wa_mesaj_id', sa.String(length=100), nullable=True),
    sa.Column('yon', sa.String(length=10), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('ai_analiz', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mulk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('sehir', sa.String(length=50), nullable=True),
    sa.Column('ilce', sa.String(length=50), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('islem_turu', sa.String(length=10), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=True),
    sa.Column('metrekare', sa.Float(), nullable=True),
    sa.Column('oda_sayisi', sa.String(length=10), nullable=True),
    sa.Column('ada', sa.String(length=20), nullable=True),
    sa.Column('parsel', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('islem_turu', sa.String(length=10), nullable=True),
    sa.Column('butce_min', sa.Float(), nullable=True),
    sa.Column('butce_max', sa.Float(), nullable=True),
    sa.Column('tercih_notlar', sa.Text(), nullable=True),
    sa.Column('sicaklik', sa.String(length=10), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.Column('guncelleme', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('not',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('etiket', sa.String(length=50), nullable=True),
    sa.Column('tamamlandi', sa.Boolean(), nullable=True),
    sa.Column('hatirlatma', sa.DateTime(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yer_gosterme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('musteri_onay', sa.Boolean(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('onay_ip', sa.String(length=50), nullable=True),
    sa.Column('ham_veri', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri_onay_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yer_gosterme_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('kullanildi', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['yer_gosterme_id'], ['yer_gosterme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musteri_onay_token')
    op.drop_table('yer_gosterme')
    op.drop_table('not')
    op.drop_table('musteri')
    op.drop_table('mulk')
    op.drop_table('konusma')
    op.drop_table('emlakci')
    # ### end Alembic commands ###
