"""bildirim tablosu

Revision ID: c7afe58f5b21
Revises: a7d5c8da5030
Create Date: 2026-04-30 02:11:15.141458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7afe58f5b21'
down_revision = 'a7d5c8da5030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bildirim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=True),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bildirim')
    # ### end Alembic commands ###
