"""iletisim_kayit tablosu

Revision ID: c88604ffc58d
Revises: 4e3d7d6eec54
Create Date: 2026-04-30 21:21:16.808631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88604ffc58d'
down_revision = '4e3d7d6eec54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iletisim_kayit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('yon', sa.String(length=10), nullable=True),
    sa.Column('ozet', sa.Text(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iletisim_kayit')
    # ### end Alembic commands ###
