"""panel_sohbet ve panel_mesaj tablolari

Revision ID: ce18c70f4ed1
Revises: b5523360857c
Create Date: 2026-04-29 18:10:58.013041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce18c70f4ed1'
down_revision = 'b5523360857c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_sohbet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.Column('guncelleme', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_mesaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sohbet_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sohbet_id'], ['panel_sohbet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_mesaj')
    op.drop_table('panel_sohbet')
    # ### end Alembic commands ###
