"""lead ve cagri tablolari

Revision ID: e14cf58db7ac
Revises: 9055550a6f21
Create Date: 2026-04-30 01:00:45.291856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14cf58db7ac'
down_revision = '9055550a6f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('kaynak', sa.String(length=30), nullable=True),
    sa.Column('sicaklik', sa.String(length=10), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('ilk_mesaj', sa.Text(), nullable=True),
    sa.Column('son_iletisim', sa.DateTime(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cagri_kayit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('yon', sa.String(length=10), nullable=True),
    sa.Column('sure_sn', sa.Integer(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cagri_kayit')
    op.drop_table('lead')
    # ### end Alembic commands ###
