"""emlakci_dizin grup grup_uyelik grup_bildirim

Revision ID: e7a0be6e1b05
Revises: 168d6547f9bc
Create Date: 2026-05-02 02:31:15.269496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a0be6e1b05'
down_revision = '168d6547f9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emlakci_dizin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ekleyen_id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('bolge', sa.String(length=100), nullable=True),
    sa.Column('uzmanlik', sa.String(length=100), nullable=True),
    sa.Column('acente', sa.String(length=120), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ekleyen_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=120), nullable=False),
    sa.Column('slogan', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kurucu_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurucu_id'], ['emlakci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_bildirim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup_id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('mesaj', sa.String(length=200), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_uyelik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup_id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=15), nullable=True),
    sa.Column('durum', sa.String(length=15), nullable=True),
    sa.Column('portfoy_acik', sa.Boolean(), nullable=True),
    sa.Column('talep_acik', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['grup_id'], ['grup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grup_id', 'emlakci_id', name='uq_grup_emlakci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grup_uyelik')
    op.drop_table('grup_bildirim')
    op.drop_table('grup')
    op.drop_table('emlakci_dizin')
    # ### end Alembic commands ###
