"""gorev tablosu

Revision ID: f2ec55c20106
Revises: 04c0b3a051ae
Create Date: 2026-04-29 23:58:19.418318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ec55c20106'
down_revision = '04c0b3a051ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gorev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emlakci_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('oncelik', sa.String(length=10), nullable=True),
    sa.Column('durum', sa.String(length=15), nullable=True),
    sa.Column('baslangic', sa.DateTime(), nullable=True),
    sa.Column('bitis', sa.DateTime(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('mulk_id', sa.Integer(), nullable=True),
    sa.Column('detaylar', sa.JSON(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emlakci_id'], ['emlakci.id'], ),
    sa.ForeignKeyConstraint(['mulk_id'], ['mulk.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gorev')
    # ### end Alembic commands ###
