"""kredi_son_kullanma

Revision ID: f68c57f4836b
Revises: c88604ffc58d
Create Date: 2026-04-30 23:44:11.603104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68c57f4836b'
down_revision = 'c88604ffc58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emlakci', sa.Column('kredi_son_kullanma', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emlakci', 'kredi_son_kullanma')
    # ### end Alembic commands ###
